swagger: '2.0'
host: localhost:8888
basePath: /
info:
  version: 1.0.0
  title: Energetic Comunities Manager API
  description: "Se trata de un microservicio dirigido a los gestores de comunidades energéticas\n en el cual se podrán añadir nuevos miembros a las distintas comunidades así\n como crear nuevas comunidades y eliminar las ya creadas."
  
paths:
  /api/communities:
    get:
      description: Obtiene una lista con todos las comunidades en formato JSON
      summary: Obtiene todos las comunidades
      operationId: GETCommunities
      responses:
        "200":
          description: Success. Obtiene la lista de comunidades de la base
                      de datos y la devuelve.
          schema:
            type: object
            properties:
              error:
                type: boolean
              codigo:
                type: number
              mensaje:
                type: object
                        
  /api/community/{name}:
    get:
      description: Obtiene la comunidad cuyo nombre corresponde con el pasado como parámetro.
      summary: Obtiene una comunidad en específico
      operationId: getComunidadID
      parameters:
        - in: path
          name: name
          required: true
          type: string
      responses:
        "200":
          description: Success. Obtiene el miembro de la base
                      de datos y lo devuelve.
          schema:
            type: object
            properties:
              error:
                type: boolean
              codigo:
                type: number
              mensaje:
                type: object
        "404":
          description: Error. No existe ningún miembro con el DNI
                    especificado.
    post:
      description: Intenta crear una nueva comunidad con los parámetros introducidos
                  comprobando que no hay conflictos con las ya existentes
      summary: Crea una nueva comunidad
      operationId: postCommunityURL
      parameters:
        - in: path
          name: name
          required: true
          type: string
        - in: body
          name: comunidad
          description: comunidad a crear
          schema:
            type: object
            required:
              - desc
              - latitud
              - nombre
              - longitud
              - gestor_dni
            properties:
              desc:
                type: string
                description: breve descripción de la comunidad
              latitud:
                type: float
                description: latitud geográfica a la que se encuentra la comunidad
              longitud:
                type: float
                description: longitud geográfica a la que se encuentra la comunidad
              gestor_dni:
                type: string
                description: DNI del gestor encargado de la comunidad
      responses:
        "201":
          description: Success. Consigue crear la nueva comunidad
          schema:
            type: object
            properties:
              error:
                type: boolean
              codigo:
                type: number
              mensaje:
                type: object
        "404":
          description: Error. La comunidad o el DER asignado al miembro
                      no existen en la base de datos.
        "409":
          description: Error. Ya existe un miembro en la DB con el DNI
                      proporcionado.
        "400":
          description: Error. Algunos atributos de miembro no son válidos.
    delete:
      description: Elimina una comunidad existente
      summary: Elimina una comunidad existente
      operationId: deleteCommunity
      parameters:
        - in: path
          name: name
          required: true
          type: string
          description: nombre de la comunidad que se va a eliminar
      responses:
        "200":
            description: Success. La comunidad se ha eliminado
        "404":
            description: Error. La comunidad no existe en la base de datos.
            
  /api/community/{name}/add-member/{dni}:
    put:
      description: Añade un miembro existente en la base de datos a una comunidad tambien 
                      existente
      summary: Añade un miembro a una comounidad
      operationId: addMemberToCommunity
      parameters:
        - in: path
          name: name
          required: true
          type: string
          description: nombre de la comunidad en la que se inserta el miembro
        - in: path
          name: dni
          required: true
          type: string
          description: DNI del miembro a insertar
      responses:
        "201":
          description: Success. El miembro se une a la comunidad
          schema:
            type: object
            properties:
              error:
                type: boolean
              codigo:
                type: number
              mensaje:
                type: object
        "404":
            description: Error. La comunidad o el miembro no existen en la base de datos.